hl.on("hyprland.start", function()
    if os.getenv("HYPR_NO_PLUGINS") ~= "1" then
        hl.exec_cmd("hyprpm reload -n; xwl-cursor-fixctl load")
    end
    hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE GSK_RENDERER GDK_DISABLE && systemctl --user start hyprland-session.target")
    hl.exec_cmd("mako")
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("~/.config/ironbar/scripts/ironbar-control.sh start left")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("copyq")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd([[printf 'Xft.dpi: 154\nXcursor.theme: %s\nXcursor.size: %s\n' "${XCURSOR_THEME:-BreezeX-RosePine-Linux}" "${XCURSOR_SIZE:-28}" | xrdb -merge]])
    hl.exec_cmd("sleep 2 && xsetroot -cursor_name left_ptr")
    hl.exec_cmd("hyprsunset -t 6500 -g 100")
end)

hl.on("hyprland.shutdown", function()
    os.execute("systemctl --user stop hyprland-session.target && sleep 0.1")
end)
