hl.on("hyprland.start", function()
    -- Bring up systemd graphical-session.target so xdg-desktop-portal can start
    -- (portal's Requisite=graphical-session.target; without this, Flatpak apps
    --  like Spotify can't open external login URLs in the browser via OpenURI)
    hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("elephant")
    hl.exec_cmd("mako")
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("ironbar -c ~/.config/ironbar/top/config.toml")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("copyq")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd([[echo "Xft.dpi:192" | xrdb -merge]])
    hl.exec_cmd("hyprsunset -t 6500 -g 100")
--    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("python3 ~/scripts/sub-proxy.py")
end)
