hl.env("XCURSOR_THEME",    "BreezeX-RosePine-Linux")
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("QT_IM_MODULE",     "fcitx")
hl.env("XMODIFIERS",       "@im=fcitx")
hl.env("LANG",             "zh_CN.UTF-8")
hl.env("LANGUAGE",         "zh_CN:en_US")
hl.env("GSK_RENDERER",     "gl")
hl.env("GDK_DISABLE",      "vulkan")
