[config]

[templates.waybar]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/waybar/colors.css"

[templates.hyprland]
input_path = "~/.config/matugen/templates/colors-hyprland.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml"
output_path = "~/.config/starship.toml"

[templates.mako]
input_path = "~/.config/matugen/templates/mako"
output_path = "~/.config/mako/config"

[templates.wlogout]
input_path = "~/.config/matugen/templates/wlogout.css"
output_path = "~/.config/wlogout/style.css"

[templates.fastfetch]
input_path = "~/.config/matugen/templates/config.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock.conf"

[templates.prelock]
input_path = "~/.config/matugen/templates/prelock-color.txt"
output_path = "~/.config/hypr/lock_animation/prelock_color"
