position = "top"
height = 24
margin_top = 4
margin_bottom = 4
ironvar_defaults.spotify_running = "false"


[[start]]
type = "workspaces"
hidden = ["special:spotify"]


[[start]]
type = "label"
name = "prev"
label = "󰒮"
show_if = "#spotify_running"
tooltip = "Previous"
on_click_left = "~/.config/ironbar/scripts/modules/spotify.sh previous"

[[start]]
type = "script"
class = "play-pause"
mode = "watch"
show_if = "#spotify_running"
cmd = "~/.config/ironbar/scripts/modules/spotify.sh watch"
tooltip = "{{~/.config/ironbar/scripts/modules/spotify.sh metadata}}"
on_click_left = "~/.config/ironbar/scripts/modules/spotify.sh toggle"

[[start]]
type = "label"
name = "next"
label = "󰒭"
show_if = "#spotify_running"
tooltip = "Next"
on_click_left = "~/.config/ironbar/scripts/modules/spotify.sh next"



[[center]]
type = "script"
class = "custom-battery"
mode = "poll"
interval = 30000
cmd = "~/.config/ironbar/scripts/modules/battery.sh"

[[center]]
type = "script"
class = "volume"
mode = "watch"
cmd = "~/.config/ironbar/scripts/modules/volume.sh watch"
on_scroll_up   = "~/.config/ironbar/scripts/modules/volume.sh up"
on_scroll_down = "~/.config/ironbar/scripts/modules/volume.sh down"
on_click_left  = "~/.config/ironbar/scripts/modules/volume.sh open"
on_click_right = "~/.config/ironbar/scripts/modules/volume.sh mute"


[[center]]
type = "script"
class = "brightness"
mode = "poll"
interval = 500
cmd = "~/.config/ironbar/scripts/modules/brightness.sh status"
on_scroll_up = "~/.config/ironbar/scripts/modules/brightness.sh up"
on_scroll_down = "~/.config/ironbar/scripts/modules/brightness.sh down"


[[center]]
type = "script"
class = "clock"
mode = "watch"
cmd = "~/.config/ironbar/scripts/modules/clock.sh watch"
tooltip = "{{~/.config/ironbar/scripts/modules/clock.sh date}}"


[[center]]
type = "script"
name = "power-btn"
class = "power-btn"
mode = "watch"
cmd = "~/.config/ironbar/scripts/modules/power-profile.sh watch"
tooltip = "{{~/.config/ironbar/scripts/modules/power-profile.sh current}}"
on_click_left = "~/.config/ironbar/scripts/modules/power-profile.sh toggle"


[[center]]
type = "script"
class = "bluetooth"
mode = "watch"
cmd = "~/.config/ironbar/scripts/modules/bluetooth.sh watch"
tooltip = "{{~/.config/ironbar/scripts/modules/bluetooth.sh tooltip}}"
on_click_left = "~/.config/ironbar/scripts/modules/bluetooth.sh open"


[[center]]
type = "script"
class = "longshot"
mode = "watch"
cmd = "/home/horizon/Projects/python-projects/hypr-longshot/.venv/bin/python /home/horizon/Projects/python-projects/hypr-longshot/longshot.py watch --icon"
on_click_left = "/home/horizon/Projects/python-projects/hypr-longshot/.venv/bin/python /home/horizon/Projects/python-projects/hypr-longshot/longshot.py toggle"
on_click_right = "/home/horizon/Projects/python-projects/hypr-longshot/.venv/bin/python /home/horizon/Projects/python-projects/hypr-longshot/longshot.py cancel"


[[center]]
type = "script"
class = "cava"
mode = "watch"
cmd = "~/.config/ironbar/scripts/cava.sh"



[[end]]
type = "tray"
icon_size = 18
on_click_left = "default"
on_click_right = "menu"


[[end]]
type = "label"
name = "power"
label = "⏻"
on_click_left = "wlogout -b 3 -T 300 -B 300"
