$on_surface = rgb(e2e2e9)
$on_surface_variant = rgb(c5c6d0)
$outline_pango = ##8f9099
$primary = rgb(b0c6ff)
$primary_80 = rgba(b0c6ff80)
$primary_4d = rgba(b0c6ff4D)
$secondary_4d = rgba(c0c6dc4D)
$tertiary = rgb(e0bbdd)
$tertiary_d0 = rgba(e0bbddD0)
$tertiary_4d = rgba(e0bbdd4D)
$surface_container_b3 = rgba(1e1f25b3)
$error = rgb(ffb4ab)
$error_container = rgb(93000a)
