$on_surface = rgb(e9e0e7)
$on_surface_variant = rgb(cec3ce)
$outline_pango = ##978e97
$primary = rgb(e2b7f4)
$primary_80 = rgba(e2b7f480)
$primary_4d = rgba(e2b7f44D)
$secondary_4d = rgba(d4c0d84D)
$tertiary = rgb(f5b7b6)
$tertiary_d0 = rgba(f5b7b6D0)
$tertiary_4d = rgba(f5b7b64D)
$surface_container_b3 = rgba(221e23b3)
$error = rgb(ffb4ab)
$error_container = rgb(93000a)
