$on_surface = rgb(e4e1e9)
$on_surface_variant = rgb(c8c5d0)
$outline_pango = ##918f9a
$primary = rgb(c0c1ff)
$primary_80 = rgba(c0c1ff80)
$primary_4d = rgba(c0c1ff4D)
$secondary_4d = rgba(c6c4dd4D)
$tertiary = rgb(e9b9d3)
$tertiary_d0 = rgba(e9b9d3D0)
$tertiary_4d = rgba(e9b9d34D)
$surface_container_b3 = rgba(1f1f25b3)
$error = rgb(ffb4ab)
$error_container = rgb(93000a)
