# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#14140c"

# Main text color
theme[main_fg]="#e6e2d5"

# Title color for boxes
theme[title]="#cdca75"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#cbc8a4"

# Background color of selected items
theme[selected_bg]="#36352c"

# Foreground color of selected items
theme[selected_fg]="#cdca75"

# Color of inactive/disabled text
theme[inactive_fg]="#939181"  

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#cac7b6"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a4d0bc"

# Box outline colors
theme[cpu_box]="#48473a"
theme[mem_box]="#48473a"
theme[net_box]="#48473a"
theme[proc_box]="#48473a"
theme[div_line]="#48473a"

# Temperature graph colors (Primary -> Tertiary -> Error)
theme[temp_start]="#cdca75"
theme[temp_mid]="#a4d0bc"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#cdca75"
theme[cpu_mid]="#a4d0bc"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter (Reversed: Error -> Tertiary -> Primary)
theme[free_start]="#ffb4ab"
theme[free_mid]="#a4d0bc"
theme[free_end]="#cdca75"

# Mem/Disk cached meter
theme[cached_start]="#cbc8a4"
theme[cached_mid]="#49482d"
theme[cached_end]="#cdca75"

# Mem/Disk available meter
theme[available_start]="#ffb4ab"
theme[available_mid]="#a4d0bc"
theme[available_end]="#cdca75"

# Mem/Disk used meter
theme[used_start]="#cdca75"
theme[used_mid]="#a4d0bc"
theme[used_end]="#ffb4ab"

# Download graph colors
theme[download_start]="#cdca75"
theme[download_mid]="#cbc8a4"
theme[download_end]="#a4d0bc"

# Upload graph colors
theme[upload_start]="#a4d0bc"
theme[upload_mid]="#cbc8a4"
theme[upload_end]="#cdca75"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#cdca75"
theme[process_mid]="#a4d0bc"
theme[process_end]="#ffb4ab"
