# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="{{colors.surface.default.hex}}"

# Main text color
theme[main_fg]="{{colors.on_surface.default.hex}}"

# Title color for boxes
theme[title]="{{colors.primary.default.hex}}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{palettes.contrary._80.hex}}"

# Background color of selected items
theme[selected_bg]="{{colors.surface_container_highest.default.hex}}"

# Foreground color of selected items
theme[selected_fg]="{{palettes.contrary._90.hex}}"

# Color of inactive/disabled text
theme[inactive_fg]="{{colors.outline.default.hex}}"  

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="{{colors.on_surface_variant.default.hex}}"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="{{palettes.contrary._80.hex}}"

# Box outline colors
theme[cpu_box]="{{colors.outline_variant.default.hex}}"
theme[mem_box]="{{palettes.contrary._30.hex}}"
theme[net_box]="{{colors.outline_variant.default.hex}}"
theme[proc_box]="{{palettes.contrary._30.hex}}"
theme[div_line]="{{colors.outline_variant.default.hex}}"

# Temperature graph colors (Primary -> Tertiary -> Error)
theme[temp_start]="{{colors.primary.default.hex}}"
theme[temp_mid]="{{colors.tertiary.default.hex}}"
theme[temp_end]="{{colors.error.default.hex}}"

# CPU graph colors
theme[cpu_start]="{{colors.primary.default.hex}}"
theme[cpu_mid]="{{colors.tertiary.default.hex}}"
theme[cpu_end]="{{colors.error.default.hex}}"

# Mem/Disk free meter (Reversed: Error -> Tertiary -> Primary)
theme[free_start]="{{colors.error.default.hex}}"
theme[free_mid]="{{colors.tertiary.default.hex}}"
theme[free_end]="{{colors.primary.default.hex}}"

# Mem/Disk cached meter
theme[cached_start]="{{colors.secondary.default.hex}}"
theme[cached_mid]="{{palettes.contrary._70.hex}}"
theme[cached_end]="{{colors.primary.default.hex}}"

# Mem/Disk available meter
theme[available_start]="{{colors.error.default.hex}}"
theme[available_mid]="{{colors.tertiary.default.hex}}"
theme[available_end]="{{colors.primary.default.hex}}"

# Mem/Disk used meter
theme[used_start]="{{colors.primary.default.hex}}"
theme[used_mid]="{{colors.tertiary.default.hex}}"
theme[used_end]="{{colors.error.default.hex}}"

# Download graph colors
theme[download_start]="{{colors.primary.default.hex}}"
theme[download_mid]="{{colors.secondary.default.hex}}"
theme[download_end]="{{palettes.contrary._80.hex}}"

# Upload graph colors
theme[upload_start]="{{palettes.contrary._80.hex}}"
theme[upload_mid]="{{colors.secondary.default.hex}}"
theme[upload_end]="{{colors.primary.default.hex}}"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="{{colors.primary.default.hex}}"
theme[process_mid]="{{palettes.contrary._70.hex}}"
theme[process_end]="{{colors.error.default.hex}}"
