[Metadata]
Name=matugen
Version=0.1
Author=horizon
Description=Material You theme for fcitx5

[Vertical Candidate List]
Vertical Candidate List=True

[Theme]
Font=Sans 10
Color={{colors.surface.default.hex}}
BorderColor={{colors.primary.default.hex}}
BorderWidth=2

[Theme/Content]
Color={{colors.on_surface.default.hex}}

[Theme/Highlight]
Color={{colors.primary_container.default.hex}}

[Theme/Highlight/Text]
Color={{colors.on_primary_container.default.hex}}

[Theme/Caret]
Color={{colors.primary.default.hex}}
