MAIN_COLOR={{colors.secondary_fixed_dim.default.hex}}
MAIN_SHADOW={{colors.secondary_container.default.hex}}
MAIN_DARKER_SHADOW={{colors.on_secondary.default.hex}}
MAIN_HIGHLIGHT={{colors.secondary.default.hex}}
INVERSE_MAIN_COLOR={{palettes.contrary._80.hex}}
INVERSE_MAIN_HIGHLIGHT={{palettes.contrary._70.hex}}
INVERSE_MAIN_SHADOW={{palettes.contrary._30.hex}}
TRASH_PAPER={{palettes.contrary._90.hex}}
HTML_DEEP={{colors.surface_container.default.hex}}
PRESENTATION_STAND={{colors.outline.default.hex}}
AUDIO_PALE={{colors.tertiary_fixed.default.hex}}
AUDIO_DEEP={{colors.on_tertiary_container.default.hex}}
