$on_surface = rgb({{colors.on_surface.default.hex_stripped}})
$on_surface_variant = rgb({{colors.on_surface_variant.default.hex_stripped}})
$outline_pango = ##{{colors.outline.default.hex_stripped}}
$primary = rgb({{colors.primary.default.hex_stripped}})
$primary_80 = rgba({{colors.primary.default.hex_stripped}}80)
$primary_4d = rgba({{colors.primary.default.hex_stripped}}4D)
$secondary_4d = rgba({{colors.secondary.default.hex_stripped}}4D)
$tertiary = rgb({{colors.tertiary.default.hex_stripped}})
$tertiary_d0 = rgba({{colors.tertiary.default.hex_stripped}}D0)
$tertiary_4d = rgba({{colors.tertiary.default.hex_stripped}}4D)
$surface_container_b3 = rgba({{colors.surface_container.default.hex_stripped}}b3)
$error = rgb({{colors.error.default.hex_stripped}})
$error_container = rgb({{colors.error_container.default.hex_stripped}})
